### ISSUE TITLE
Add ability to capture headers from responses

### ISSUE THREAD

**Issue by zakpatterson** [dariooddenino/purescript-simple-ajax#1]
At the moment, processing other components of the responses other than the body appears out of scope. For the user of this library, it would be easiest to add this functionality by modifying the implementation of this library, since there is not a hook it appears into the response parsing logic. I'm working on a PR for this now.

**Comment by dariooddenino** [comment]
Merged #2 in v0.5.0

**Comment by zakpatterson** [comment]
Awesome!
